name: clean_flutter_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  cupertino_icons: ^1.0.6
  provider:
  equatable:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  test:
  faker:
  mocktail:
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  ios: true
  android: true
  image_path_android: lib/ui/assets/android.png
  image_path_ios: lib/ui/assets/ios.png
  adaptive_icon_background: lib/ui/assets/background.png
  adaptive_icon_foreground: lib/ui/assets/foreground.png